name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.5'  # Specify the GHC version you want to use
        cabal-version: '3.8.1.0'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-cabal-
    
    - name: Update Cabal package list
      run: cabal v2-update
    
    - name: Build project
      run: cabal v2-build
    
    - name: Run tests
      run: cabal v2-test
