name: Hlint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.hs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.hs'

jobs:
  hlint:
    name: Hlint - Linux
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run hlint
      run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s -- src/
