name: Hlint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.hs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.hs'

jobs:
  hlint:
    name: Hlint - Linux
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Run hlint
      run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s -- src/
