name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cabal:
    strategy:
      matrix:
        ghc: ['9.4.8','9.6.6','9.8.4','9.10.1']
    name: Cabal - Linux GHC ${{ matrix.ghc }}
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: cabal-${{ matrix.ghc }}-${{ hashFiles('aeson-jsonpath.cabal') }}
        restore-keys: |
          cabal-${{ matrix.ghc }}-
    
    - name: Update Cabal package list
      run: cabal v2-update
    
    - name: Build project
      run: cabal v2-build

    - name: Run tests
      run: cabal v2-test
